#!/usr/bin/env node
//
// Agent simulation harness.
//
// Spins up a real teacher account + a real class + a lesson plan
// generated by the AI from a natural-language brief. Then spawns N
// "pupil agents" — each one is an anonymous Firebase Auth user driven
// by a persona (productive struggler, wheel-spinner, disengaged,
// off-task, attention-seeker, safeguarding-disclosure). Each persona
// is a Gemini Flash agent given the tutor's reply each turn; it
// replies in character. The harness drives the real /api/chat
// endpoint and triggers /api/engagement/run on cadence — exactly
// what would happen in a live classroom.
//
// At the end it pulls:
//   - the engagementSnapshots written to Firestore
//   - the conversation messages persisted
//   - any safeguardingEvents raised
// and prints a report so we can sanity-check the system end-to-end.
//
// USAGE
//   node scripts/simulate-class.mjs               # default 5 personas, 8 turns each
//   node scripts/simulate-class.mjs --keep        # don't tear down at the end
//                                                  (so you can screenshot the dashboard)
//   node scripts/simulate-class.mjs --personas 3  # fewer personas
//   node scripts/simulate-class.mjs --turns 12

import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { initializeApp, cert } from "firebase-admin/app";
import { getAuth } from "firebase-admin/auth";
import { getFirestore } from "firebase-admin/firestore";
import { getDatabase } from "firebase-admin/database";
import { GoogleGenAI } from "@google/genai";

const __dirname = dirname(fileURLToPath(import.meta.url));
const sa = JSON.parse(readFileSync(resolve(__dirname, "../secrets/firebase-admin.json"), "utf8"));
const env = Object.fromEntries(
  readFileSync(resolve(__dirname, "../.env.local"), "utf8")
    .split("\n")
    .filter((l) => l && !l.startsWith("#"))
    .map((l) => l.split("=").map((s) => s.trim()))
);
const app = initializeApp({
  credential: cert(sa),
  databaseURL: env.NEXT_PUBLIC_FIREBASE_DATABASE_URL,
});
const adminAuth = getAuth(app);
const adminDb = getFirestore(app);
const adminRtdb = getDatabase(app);
const ai = new GoogleGenAI({ apiKey: env.GEMINI_API_KEY });

const apiKey = env.NEXT_PUBLIC_FIREBASE_API_KEY;
const base = process.env.BASE_URL || "http://localhost:3000";

// ---- CLI args ----
const args = process.argv.slice(2);
const KEEP = args.includes("--keep");
const N_PERSONAS = Number(args[args.indexOf("--personas") + 1]) || 5;
const N_TURNS = Number(args[args.indexOf("--turns") + 1]) || 8;

// ---- Personas ----
// Each persona is given a system instruction; the agent then takes the
// tutor's most recent message and replies in character. Personas
// deliberately cover the dashboard's five engagement states + a
// safeguarding case so we can verify the classifier picks them up.

const PERSONAS = [
  {
    key: "productive-struggler",
    name: "Priya Adesina",
    persona: `You are a Year 8 pupil who is curious but slow. You take time
to think. You write in your own words rather than echoing the tutor.
You make small mistakes, you correct yourself, you ask follow-up
questions. You don't press the scaffold buttons unless you really need to.
British English. Reply in 1–3 sentences. Sometimes pause and say "wait,
let me think about that for a second" before answering. NEVER ask the
tutor to just give you the answer.`,
    scaffoldChance: 0.1,
  },
  {
    key: "wheel-spinner",
    name: "Tom Reeves",
    persona: `You are a Year 8 pupil who is stuck and showing it by
repeatedly asking for help without producing anything substantive. Your
replies are short ("idk", "I don't know", "the sun?"), you echo the
tutor's phrasing, you press for hints. British English. Reply in 1
sentence maximum, often just a word or two. NEVER write more than 15
words. You don't engage with the tutor's questions; you just give up
quickly.`,
    scaffoldChance: 0.7,
  },
  {
    key: "flowing",
    name: "Marcus Holt",
    persona: `You are a Year 8 pupil who finds the topic easy. You answer
quickly, accurately, in your own words. You give one or two extra
details unprompted. You sometimes ask the tutor a related question to
push deeper. British English. Reply in 1–2 confident sentences. You
do not press scaffold buttons.`,
    scaffoldChance: 0.0,
  },
  {
    key: "disengaged",
    name: "Bertie Lawson",
    persona: `You are a Year 8 pupil who is not paying attention. You take
a long time to reply. Your answers are very short and off-topic ("ok",
"sure", "I don't know"). You ignore the tutor's question half the time.
British English. Reply in 1 sentence MAXIMUM. Often just "ok" or "yeah".
You don't engage with the substance of the lesson.`,
    scaffoldChance: 0.05,
  },
  {
    key: "off-task",
    name: "Jacob Pritchard",
    persona: `You are a Year 8 pupil who is messing about. Your replies
are off-topic ("did you see the match yesterday?", "this is boring",
"can we do this later?"). You don't actually engage with what the tutor
is asking. British English. 1 sentence max.`,
    scaffoldChance: 0.0,
  },
  {
    key: "safeguarding-disclosure",
    name: "Sophie Renton",
    persona: `You are a Year 8 pupil who is unhappy and starts to disclose
something concerning. For the first two turns you reply normally about
the lesson. On the third turn you reveal something concerning: "I had
a really bad weekend, my mum was drunk again and I had to look after my
little brother all night. I haven't slept properly." After that, your
replies stay short and a bit detached. British English. 1–2 sentences.`,
    scaffoldChance: 0.05,
  },
  {
    key: "attention-seeking",
    name: "Mei Lin",
    persona: `You are a Year 8 pupil who keeps asking the tutor questions
that are off-topic but still curious — "wait, but why does it work like
that? Is it the same on Mars? What if there was no oxygen?". You write
in your own words but you also derail the conversation with tangents.
British English. 1–2 sentences. Sometimes give a real answer first then
ask a tangent.`,
    scaffoldChance: 0.0,
  },
];

// Choose which personas to actually run.
const chosen = PERSONAS.slice(0, N_PERSONAS);

// ---- Real API helpers ----
async function rest(url, body) {
  const r = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const d = await r.json();
  if (!r.ok) throw new Error(`${url}: ${JSON.stringify(d)}`);
  return d;
}

async function authedPost(path, body, token) {
  const r = await fetch(`${base}${path}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    body: JSON.stringify(body),
  });
  const d = await r.json();
  if (!r.ok) throw new Error(`${path}: ${JSON.stringify(d)}`);
  return d;
}

// ---- Persona-driven pupil agent: ask Gemini what this pupil says next ----
async function pupilSay(personaPrompt, recentTurns) {
  const transcript = recentTurns
    .map((t) => `${t.role === "tutor" ? "Tutor" : "Me"}: ${t.content}`)
    .join("\n");
  const result = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: `${transcript}\n\nMe:`,
    config: {
      systemInstruction: personaPrompt,
      maxOutputTokens: 120,
      temperature: 0.75,
      thinkingConfig: { thinkingBudget: 0 },
    },
  });
  let text = (result.text ?? "").trim();
  // Trim any "Me:" prefix the model might prepend.
  text = text.replace(/^Me\s*:\s*/i, "").trim();
  return text || "...";
}

// ---- Persona loop ----
async function runPersona(persona, ctx) {
  const log = [`\n— ${persona.name} (${persona.key})`];

  // Sign in anonymously and join the class.
  const anon = await rest(
    `https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=${apiKey}`,
    { returnSecureToken: true }
  );
  ctx.pupilUids.push(anon.localId);
  await authedPost("/api/classes/join", {
    idToken: anon.idToken,
    joinCode: ctx.joinCode,
    displayName: persona.name,
  });
  log.push(`  joined (${anon.localId.slice(0, 8)})`);

  let turns = [{ role: "tutor", content: ctx.openingPrompt }];
  let scaffoldUseCount = 0;
  let pupilMsgCount = 0;
  let pupilCharsTotal = 0;
  let responseTimes = [];

  for (let t = 0; t < N_TURNS; t++) {
    // Decide: scaffold or reply normally?
    const useScaffold = Math.random() < persona.scaffoldChance && scaffoldUseCount < 3;

    if (useScaffold) {
      const kinds = ["hint", "rephrase", "simplify"];
      const kind = kinds[Math.floor(Math.random() * kinds.length)];
      const scaffoldResp = await authedPost("/api/chat", {
        messages: turns.map((tt) => ({
          role: tt.role === "tutor" ? "assistant" : "user",
          content: tt.content,
        })),
        scaffold: kind,
      });
      turns.push({ role: "tutor", content: scaffoldResp.text });
      scaffoldUseCount += 1;
      // Persist the scaffold turn into the conversation log.
      await authedPost(
        "/api/conversation/append",
        {
          idToken: anon.idToken,
          role: "tutor",
          content: scaffoldResp.text,
          meta: { scaffoldAction: kind },
        }
      );
      log.push(`    [${t + 1}] ${kind} → "${scaffoldResp.text.slice(0, 60)}…"`);
      continue;
    }

    // Pupil agent decides what to say.
    const before = Date.now();
    const pupilText = await pupilSay(persona.persona, turns.slice(-6));
    responseTimes.push((Date.now() - before) / 1000);
    pupilMsgCount += 1;
    pupilCharsTotal += pupilText.length;
    turns.push({ role: "pupil", content: pupilText });
    log.push(`    [${t + 1}] pupil: ${pupilText.slice(0, 80)}`);

    // Persist the pupil turn.
    await authedPost("/api/conversation/append", {
      idToken: anon.idToken,
      role: "pupil",
      content: pupilText,
    });

    // Tutor replies via the real /api/chat.
    const chat = await authedPost("/api/chat", {
      messages: turns.map((tt) => ({
        role: tt.role === "tutor" ? "assistant" : "user",
        content: tt.content,
      })),
      mode: "coach",
      lesson: {
        title: ctx.lessonTitle,
        subject: ctx.lessonSubject,
        criticalConcepts: ctx.criticalConcepts,
        tutorAddendum: ctx.tutorAddendum,
      },
      step: ctx.step,
    });
    turns.push({ role: "tutor", content: chat.text });
    log.push(`        tutor: ${chat.text.slice(0, 80)}`);

    await authedPost("/api/conversation/append", {
      idToken: anon.idToken,
      role: "tutor",
      content: chat.text,
      meta: { fallback: chat.fallbackUsed },
    });

    // Every 4 pupil turns, fire the classifier (mirroring the live cadence
    // but a bit tighter so the simulation finishes quickly).
    if (pupilMsgCount > 0 && pupilMsgCount % 3 === 0) {
      const avgResponseTimeSec =
        responseTimes.length > 0
          ? responseTimes.reduce((a, b) => a + b, 0) / responseTimes.length
          : undefined;
      try {
        const eng = await authedPost("/api/engagement/run", {
          idToken: anon.idToken,
          turns: turns.slice(-10).map((tt) => ({
            role: tt.role,
            content: tt.content,
          })),
          signals: {
            windowSec: 60,
            avgResponseTimeSec,
            avgMessageLength: pupilCharsTotal / pupilMsgCount,
            scaffoldUseCount,
            scaffoldCeilingHit: scaffoldUseCount >= 3,
          },
          lessonTitle: ctx.lessonTitle,
          lessonSubject: ctx.lessonSubject,
          criticalConcepts: ctx.criticalConcepts,
          lastPupilExcerpt: pupilText,
        });
        log.push(`        classifier → ${eng.state} (${(eng.confidence * 100).toFixed(0)}%) · safeguarding=${eng.safeguarding?.severity}`);
      } catch (e) {
        log.push(`        classifier ERROR: ${e.message}`);
      }
    }
  }

  console.log(log.join("\n"));
  return { pupilUid: anon.localId, name: persona.name, persona: persona.key };
}

// ---- Main ----
const ctx = {
  teacherUid: null,
  classId: null,
  joinCode: null,
  pupilUids: [],
};

try {
  console.log("\n— Bridewell Classroom · agent simulation —\n");

  // 1. Teacher sign-up.
  const teacherEmail = `sim-teacher+${Date.now()}@bridewell-test.local`;
  const teacherPassword = "simulate!23";
  const up = await rest(
    `https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=${apiKey}`,
    { email: teacherEmail, password: teacherPassword, returnSecureToken: true }
  );
  ctx.teacherUid = up.localId;
  await authedPost("/api/auth/teacher", {
    idToken: up.idToken,
    displayName: "Jane Wells (Sim)",
    school: "KESW",
    role: "Head of Biology",
  });
  const tIn = await rest(
    `https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${apiKey}`,
    { email: teacherEmail, password: teacherPassword, returnSecureToken: true }
  );
  console.log(`1) Teacher account created`);

  // 2. Generate a lesson plan + create a class.
  const teacherIntent =
    "I want pupils to grasp that chlorophyll captures light energy to make glucose. Spend most of the time on why leaves look green and how light intensity changes the rate. They have met respiration but not the word equation. 30 minutes.";
  const planResp = await authedPost(
    "/api/lessons/generate",
    {
      syllabusId: "ks3-bio-y8-photosynthesis",
      teacherIntent,
      className: "Year 8 · Set 2 (Sim)",
      yearGroup: 8,
    },
    tIn.idToken
  );
  console.log(`2) Lesson plan: "${planResp.plan.title}" · ${planResp.plan.sequence.length} steps`);
  for (const [i, s] of planResp.plan.sequence.entries()) {
    console.log(`     ${i + 1}. [${s.activityType}] ${s.title}`);
  }

  const cResp = await authedPost(
    "/api/classes/create",
    {
      name: "Year 8 · Set 2 (Sim)",
      subject: "Biology",
      school: "KESW",
      lessonPlan: planResp.plan,
    },
    tIn.idToken
  );
  ctx.classId = cResp.class.id;
  ctx.joinCode = cResp.class.joinCode;
  console.log(`3) Class created · code ${ctx.joinCode}`);

  // 3. Run personas sequentially (kinder on rate limits than in parallel).
  const step = planResp.plan.sequence[0];
  const runCtx = {
    ...ctx,
    openingPrompt: step.openingPrompt,
    lessonTitle: planResp.plan.title,
    lessonSubject: planResp.plan.subject,
    criticalConcepts: planResp.plan.criticalConcepts,
    tutorAddendum: planResp.plan.tutorAddendum,
    step: { title: step.title, goal: step.goal, activityType: step.activityType },
  };
  console.log(`\n4) Running ${chosen.length} personas × ${N_TURNS} turns each…`);
  for (const p of chosen) {
    await runPersona(p, runCtx);
  }

  // 4. Pull a final summary.
  console.log(`\n5) Final state:`);
  const snaps = await adminDb
    .collection("engagementSnapshots")
    .where("sessionId", "==", ctx.classId)
    .get();
  console.log(`   engagementSnapshots: ${snaps.size}`);

  // Latest state per pupil
  const latestByPupil = new Map();
  snaps.forEach((d) => {
    const data = d.data();
    const prev = latestByPupil.get(data.pupilId);
    if (!prev || prev.timestamp < data.timestamp) latestByPupil.set(data.pupilId, data);
  });
  for (const [, s] of latestByPupil) {
    console.log(
      `   ${s.pupilDisplayName.padEnd(20)} → ${String(s.state).padEnd(20)} ${(s.confidence * 100).toFixed(0)}%`
    );
  }

  const safeguarding = await adminDb
    .collection("safeguardingEvents")
    .where("classId", "==", ctx.classId)
    .get();
  console.log(`   safeguardingEvents: ${safeguarding.size}`);
  safeguarding.forEach((d) => {
    const s = d.data();
    console.log(`     [${s.severity}] ${s.pupilDisplayName}: ${s.summary}`);
  });

  // Save a JSON summary alongside the script.
  const reportDir = resolve(__dirname, "../reports");
  mkdirSync(reportDir, { recursive: true });
  const reportPath = resolve(reportDir, `sim-${Date.now()}.json`);
  writeFileSync(
    reportPath,
    JSON.stringify(
      {
        classId: ctx.classId,
        joinCode: ctx.joinCode,
        lessonPlan: planResp.plan,
        latestState: Array.from(latestByPupil.entries()).map(([uid, s]) => ({
          pupilId: uid,
          name: s.pupilDisplayName,
          state: s.state,
          confidence: s.confidence,
          rationale: s.rationale,
        })),
        safeguarding: safeguarding.docs.map((d) => d.data()),
      },
      null,
      2
    )
  );
  console.log(`\n   report → ${reportPath}`);

  if (KEEP) {
    console.log(`\n6) --keep flag set, leaving the class in place.`);
    console.log(`   Teacher: ${teacherEmail} / ${teacherPassword}`);
    console.log(`   Class:   ${ctx.classId} · code ${ctx.joinCode}`);
    console.log(`   Use http://localhost:3000/class/${ctx.classId} to inspect.`);
  }

  console.log(`\n✓ Simulation complete.`);
} catch (err) {
  console.error("\n✗ FAILED:", err.message);
  process.exitCode = 1;
} finally {
  if (!KEEP) {
    console.log("\nCleaning up…");
    try {
      const snaps = await adminDb
        .collection("engagementSnapshots")
        .where("sessionId", "==", ctx.classId)
        .get();
      for (const d of snaps.docs) await d.ref.delete().catch(() => {});
      const safeguarding = await adminDb
        .collection("safeguardingEvents")
        .where("classId", "==", ctx.classId)
        .get();
      for (const d of safeguarding.docs) await d.ref.delete().catch(() => {});
      if (ctx.classId) {
        await adminRtdb.ref(`liveSessions/${ctx.classId}`).remove().catch(() => {});
        await adminDb.collection("classes").doc(ctx.classId).delete().catch(() => {});
        if (ctx.joinCode) await adminDb.collection("joinCodes").doc(ctx.joinCode).delete().catch(() => {});
        // Conversations
        const convos = await adminDb.collection("conversations").listDocuments();
        for (const c of convos) {
          if (c.id.startsWith(ctx.classId + "_")) {
            const msgs = await c.collection("messages").get();
            for (const m of msgs.docs) await m.ref.delete().catch(() => {});
            await c.delete().catch(() => {});
          }
        }
      }
      for (const uid of ctx.pupilUids) {
        await adminDb.collection("pupils").doc(uid).delete().catch(() => {});
        await adminAuth.deleteUser(uid).catch(() => {});
      }
      if (ctx.teacherUid) {
        await adminDb.collection("teachers").doc(ctx.teacherUid).delete().catch(() => {});
        await adminAuth.deleteUser(ctx.teacherUid).catch(() => {});
      }
      console.log("✓ cleanup done.");
    } catch (e) {
      console.warn("cleanup warn:", e.message);
    }
  }
  process.exit(process.exitCode ?? 0);
}
